name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build
        run: make
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: deploy
        run: bash scripts/update-gh-pages.sh
